### ISSUE TITLE
Multiple Instances of Quill on one Page

### ISSUE THREAD

**Issue by mohitsud** [cloudcreativity/ember-quill#1]
Awesome Plug-In. THANK YOU!!!

Is it possible to have multiple instances of the quill editor on the same page, and be able to use the quill-service to setContents of a specific instance?

**Comment by lindyhopchris** [comment]
Hi! Thanks, glad you find the addon useful!

Yes this is totally possible - if you look in the `tests/dummy` folder you'll see the dummy application has multiple Quill Editors in its `application.hbs` template.

As described in the README, if you want to use the service to interact with the editor instances (e.g. using `setContents`), then you need to use the `@name` argument to give each instance a name:
https://github.com/cloudcreativity/ember-quill/blob/develop/README.md#quill-service

You would then provide the name as the first argument when calling `setContents`:
https://github.com/cloudcreativity/ember-quill/blob/develop/addon/services/quill.js#L135

Closing this as this is documented in the *Quill Service* section of the readme.

**Comment by mohitsud** [comment]
Thank you! I appreciate the detailed reply.
